[package]
name = "dahl-roxido"
version = "0.4.0"
authors = ["David B. Dahl <dahl@stat.byu.edu>"]
edition = "2018"
description = "R packaged based on Rust"
homepage = "https://dahl.byu.edu"
license = "MIT OR Apache-2.0"

[dependencies]
libR-sys = "0.2.1"
rand_pcg = "0.3.0"
